//
//  GeneratedSceneDraft.swift
//  ReTakeAi
//

import Foundation

struct GeneratedSceneDraft: Identifiable, Hashable {
    let id: UUID
    var orderIndex: Int
    var scriptText: String
    /// Expected duration (seconds) for this scene.
    var expectedDurationSeconds: Int
    /// Optional per-scene direction metadata (if generated by AI).
    var direction: AIDirection?

    init(
        id: UUID = UUID(),
        orderIndex: Int,
        scriptText: String,
        expectedDurationSeconds: Int,
        direction: AIDirection? = nil
    ) {
        self.id = id
        self.orderIndex = orderIndex
        self.scriptText = scriptText
        self.expectedDurationSeconds = expectedDurationSeconds
        self.direction = direction
    }
}


